org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.java.home=C\:\\\\Program Files\\\\Android\\\\Android Studio1\\\\jbr
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
# Explicitly set the home to resolve conflict between environment variables
# systemProp.ANDROID_USER_HOME=C:/Users/ACER/.android
# systemProp.ANDROID_PREFS_ROOT=C:/Users/ACER/.android
